language: node_js
node_js:
  - node

branches:
  only:
    - master

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

before_script:
  - npm install -g --silent @angular/cli
  - npm install -g --silent firebase-tools

script:
  - ng test --single-run
  - ng e2e
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
