language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

before_script:
  - npm install -g @angular/cli

script:
  - ng test --single-run
  - ng e2e

